# Generated by Django 6.1 on 2026-08-13 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalleRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colonia_o_zona', models.CharField(max_length=100)),
                ('tipo_riesgo', models.CharField(choices=[('inclinacion', 'Inclinación Extrema'), ('terraceria', 'Terracería / Baches'), ('infraestructura', 'Tope Rompe-Cárter / Inundación')], max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(max_length=30)),
                ('tipo_registro', models.CharField(choices=[('viaje', 'Viaje Regular'), ('bono', 'Bono o Incentivo')], max_length=20)),
                ('distancia_km', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('tiempo_minutos', models.IntegerField(default=0)),
                ('monto_bruto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('gasto_gasolina', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=8)),
                ('gasto_desgaste', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=8)),
                ('impuestos_sat', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=8)),
                ('ganancia_neta_viaje', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=8)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
