# Generated by Django 6.1 on 2026-08-13 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calleriesgo',
            name='latitud',
            field=models.DecimalField(decimal_places=6, default=19.432608, max_digits=9),
        ),
        migrations.AddField(
            model_name='calleriesgo',
            name='longitud',
            field=models.DecimalField(decimal_places=6, default=99.133208, max_digits=9),
        ),
    ]
