# Generated by Django 6.1 on 2026-08-14 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_calleriesgo_latitud_calleriesgo_longitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calleriesgo',
            name='longitud',
            field=models.DecimalField(decimal_places=6, default=-99.133208, max_digits=9),
        ),
        migrations.AlterModelTable(
            name='calleriesgo',
            table='core_calleriesgo',
        ),
        migrations.AlterModelTable(
            name='registrofinanciero',
            table='core_registrofinanciero',
        ),
    ]
