# Generated by Django 6.1 on 2026-08-14 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_calleriesgo_longitud_alter_calleriesgo_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calleriesgo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='registrofinanciero',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
