# Generated by Django 6.1 on 2026-08-15 19:44

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_calleriesgo_activo_registrofinanciero_activo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calleriesgo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrofinanciero',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PerfilConductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo_carro', models.CharField(default='Chevrolet Spark 2016', max_length=50)),
                ('rendimiento_km_litro', models.DecimalField(decimal_places=1, default=Decimal('14.0'), max_digits=4)),
                ('costo_gasolina_litro', models.DecimalField(decimal_places=2, default=Decimal('24.50'), max_digits=5)),
                ('renta_semanal', models.DecimalField(decimal_places=2, default=Decimal('1900.00'), max_digits=7)),
                ('costo_desgaste_km', models.DecimalField(decimal_places=2, default=Decimal('0.40'), max_digits=4)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_perfilconductor',
            },
        ),
    ]
